version: '3.8'

services:
  api-gateway:
    build: ./backend/services/api-gateway
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - AUTH_SERVICE_URL=http://auth-service:4001
      - PRODUCT_SERVICE_URL=http://product-service:4002
      - CART_SERVICE_URL=http://cart-service:4003
    depends_on:
      - auth-service
      - product-service
      - cart-service

  auth-service:
    build: ./backend/services/auth-service
    environment:
      - PORT=4001
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=secret_ecom

  product-service:
    build: ./backend/services/product-service
    environment:
      - PORT=4002
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  cart-service:
    build: ./backend/services/cart-service
    environment:
      - PORT=4003
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=secret_ecom

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
