services:
  - type: web
    name: api-gateway
    env: node
    rootDir: backend/services/api-gateway
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: AUTH_SERVICE_URL
        fromService:
          type: web
          name: auth-service
          envVarKey: RENDER_EXTERNAL_URL
      - key: PRODUCT_SERVICE_URL
        fromService:
          type: web
          name: product-service
          envVarKey: RENDER_EXTERNAL_URL
      - key: CART_SERVICE_URL
        fromService:
          type: web
          name: cart-service
          envVarKey: RENDER_EXTERNAL_URL

  - type: web
    name: auth-service
    env: node
    rootDir: backend/services/auth-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        value: secret_ecom

  - type: web
    name: product-service
    env: node
    rootDir: backend/services/product-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString

  - type: web
    name: cart-service
    env: node
    rootDir: backend/services/cart-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        value: secret_ecom

  - type: redis
    name: redis-cache
    ipAllowList: []
